---
title: "lesson3.rmd"
author: "Yifei"
date: "January 29, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Reading in Data
```{r}
getwd()
list.files()
pf <- read.csv('pseudo_facebook.tsv', sep= '\t')
```

```{r}
library(ggplot2)
install.packages('ggthemes', dependencies = TRUE)
library(ggthemes)
```

```{r}
names(pf)
theme_set(theme_minimal(24)) 
qplot(x = dob_day, data = pf) + 
  scale_x_continuous(breaks=1:31) +
  facet_wrap(~dob_month)
```
```{r}
# qplot(x = friend_count, data = pf, xlim = c(0, 1000))

qplot(x = friend_count, data = subset(pf, !is.na(gender)), binwidth = 25) +
  scale_x_continuous(limits = c(0, 1000), breaks = seq(0, 1000, 50)) +
  facet_wrap(~gender)
```

```{r}
table(pf$gender)
by(pf$friend_count, pf$gender, summary)
```

## Tenure
```{r}
qplot(x = tenure/365, data = pf, 
      xlab = 'Number of years using Facebook',
      ylab = 'Number of users in sample',
      binwidth = .25, 
      color = I('black'), fill = I('#099DD9')) +
  scale_x_continuous(breaks = seq(1, 7, 1), limits = c(0, 7))
```


## User Ages
```{r}
qplot(x = age, data = pf,
      xlab = 'Ages',
      ylab = 'Number of users',
      binwidth = 1,
      color = I('black'), fill = I('#099DD9')) +
  scale_x_continuous(breaks = seq(0, 100, 10))
```

## Transforming Data
```{r}
install.packages('gridExtra')
library(gridExtra)

p1 <- qplot(x = friend_count, data = pf)
p2 <- qplot(x = log10(friend_count+1), data = pf)
p3 <- qplot(x = sqrt(friend_count), data = pf)

grid.arrange(p1, p2, p3, ncol = 1)

summary(pf$friend_count)
summary(log10(pf$friend_count))
summary(sqrt(pf$friend_count))
```

## Transforming Data Alternate Solution
## Use scales!
```{r}
p1 <- ggplot(aes(x = friend_count), data = pf) +geom_histogram()
p2 <- p1 + scale_x_log10()
p3 <- p1 + scale_x_sqrt()
grid.arrange(p1, p2, p3, ncol = 1)

```

## Frequency polygons
```{r}
ggplot(aes(x = friend_count, y = ..count../sum(..count..)), 
       data = subset(pf, !is.na(gender))) +
       geom_freqpoly(aes(color = gender), binwidth = 10) +
       scale_x_continuous(limits = c(0, 1000), breaks = seq(0, 1000, 50)) +
       xlab('Friend Count') +
       ylab('Proportion of users with that friend count')
```

## Box plot
```{r}
qplot(x = gender, y = friend_count,
      data = subset(pf, !is.na(gender)),
      geom = 'boxplot') +
  coord_cartesian(ylim = c(0, 1000))

by(pf$friend_count, pf$gender, summary)
```
```{r}
qplot(x = gender, y = friendships_initiated,
      data = subset(pf, !is.na(gender)),
      geom = 'boxplot') +
  coord_cartesian(ylim = c(0, 150))

by(pf$friendships_initiated, pf$gender, summary)
```

## Getting Logical
```{r}
mobile_check_in <- NA
pf$mobile_check_in <- ifelse(pf$mobile_likes>0, 1, 0)
pf$mobile_check_in <- factor(pf$mobile_check_in)
summary(pf$mobile_check_in)

```
What percent of check in using mobile? 64%
summary(pf$mobile_check_in)
sum(pf$mobile_check_in == 1) / length(pf$mobile_check_in)
```

